
######################################################

# Copyright (c) 2003-2020, Ansys, Inc. All rights reserved.  

# Unauthorized use, distribution, or duplication is prohibited.  
# This product is subject to U.S. laws governing export and re-export.  

# For full Legal Notice, see documentation.

######################################################

## This quality assurance (QA) script file tests the photonic elements
## generated using cml-compiler's 'wg_parameterized' photonic model

## This is a top level script file that calls multiple sub-scripts
clear;
cd(filedirectory(which(currentscriptname))+'/QA');

### QA description
?QA_description = "Testing:
1. Test set-up script runs without error
2. Custom QA test
";

### Run individual subtests

# 1. Set-up Script Test
feval("scripted_element_setup_script_qa.lsf");

# 2. Custom Tests
try{
    feval("../scripted_element_custom_qa.lsf");
} catch(msg);

if (msg!=""){
    ? "Warning: Custom test not found " + source_directory + "/" + "scripted_element_custom_qa.lsf" ;
}



### Display the final message in Script prompt
?endl;
if(error_count>0){
    ?"error_count = " + num2str(error_count);
}
else{
    ?"All tests passed.";
}
pause(2);